### ISSUE TITLE
Not blocking ads via router setup. 

### ISSUE THREAD

**Issue by Red-Baran** [mtverlee/NextDNSManager#10]
If I use adguard (android) with private dns I pretty much get 100% score on https://d3ward.github.io/toolz/adblock.html but as soon as I disable adguard and just use the private dns I have set up on my router, I only have 3% blocked.
I have several lists set up including the most recommended ones. As well as pretty much every adblocking/privacy option available with allow affiliates and trackers disabled.

This happens on all devices on my network. The correct dns is set on my crappy eero router and my IP is set correctly on nextdns.

Any advise would be helpful.

**Comment by mtverlee** [comment]
Hi, unfortunately this isn't really the correct forum for this sort of question. I suggest you try and post this question on the subreddit for NextDNS. You can find that [here](https://reddit.com/r/nextdns).
