### ISSUE TITLE
Dark Mode 

### ISSUE THREAD

**Issue by Red-Baran** [mtverlee/NextDNSManager#11]
Requesting the ability to switch from system default to dark/light mode.

Ps. 
Sorry not a bug but I don't see how to set as an enhancement request

Thank you

**Comment by Jcat44** [comment]
It now has dark mode 👍

**Comment by Jcat44** [comment]
Shame the main site doesn't offer dark mode.. blows your eyes out at night.. thankfully this app has it

**Comment by mtverlee** [comment]
@Red-Baran Currently the app follows the system theme to determine is dark mode should be used, however I can add a manual toggle to override that if that's what you're asking for.

**Comment by Red-Baran** [comment]
> 
Yes you are correct. 
That would be awesome! Very much appreciated.

**Comment by mtverlee** [comment]
That's alright, I'll close it when it's completed.

**Comment by mtverlee** [comment]
This has been added as of version 4.3.8, which is rolling out now. Thanks!
