### ISSUE TITLE
Mention correct details in the play store contacts

### ISSUE THREAD

**Issue by smonsec** [mtverlee/NextDNSManager#7]
I came across this app while searching for official app, but I was reluctant to use it as there was no contact details except for the unfinished filler website and an email.

It was a big red flag for me, as I don't wanna trust a close sourced 3rd party about my DNS queries.

Today morning I thought I should just use the domain in the email to find who is the developer behind the app, and to my luck here I am.

So, Kindly do update the developer contact on the play store (maybe your portfolio domain/GitHub or the source code for the app) untill you publish your app on the Fdroid. Also maybe mention in the description about the open nature of the app.
Thanks,

**Comment by mtverlee** [comment]
Hello,

First of all, thank you for checking out the app. If you do decide to use it, I hope you find it as useful and convenient.

Second of all, this project is completely open source and always has been. Feel free to look through the code yourself, there is nothing to be worried about. NextDNS is a privacy tool and thus this app is also privacy focused. There's no access to your data given to the app, no crazy permissions required, and should you decide to not provide anonymized debug information for use in the development project, the domains are provided to block this. There is not any Google Analytics enabled in this application, either.

A simple Google search of the app name brings you to this repository, and there is a link in the app itself, so there was no need to place a link in the Google Play listing itself, but I have gone ahead and pushed the changes you've requested, and they will be live shortly.

Again thanks for checking out the app and I hope that I have answered all your concerns. If you have more questions, feel free to reach out again.

**Comment by smonsec** [comment]
Forget to say thanks for your wonderful work. Thank you for putting it out there for everyone, this is exactly what I love about open source. Someone face an unsolved problem, develop a fix and let everybody use his work without any hesitation.

Just checked the Play store and glad to see you took those suggestions positively, and acted accordingly. Happy coding.
